WebCore/Controllers/GraphController.cs
using System.Collections.Generic;
using System.Linq;
using DatabaseModelCore.Repository;
using Microsoft.AspNetCore.Mvc;
using WebCore.Dto;

namespace WebCore.Controllers
{
    public class GraphController : Controller
    {
        private readonly UnitOfWork _unitOfWork;

        public static readonly string Name = AspRoutes.GetControllerName<GraphController>();

        public const string DistributionGraph = "distributionGraph";

        [HttpGet]
        [ActionName(DistributionGraph)]
        //[Route("Home/api/graph/GetDistributionGraph")] //make normal later
        public IEnumerable<DistributionGraphDto> GetDistributionGraph()
        {
            return _unitOfWork.QuakeEvents.GetAll()
                .GroupBy(e => e.Date.Year)
                .Select(
                    e => new
                    {
                        Year = e.Key,
                        Months = e.GroupBy(x => x.Date.ToString("MMMM"))
                            .Select(
                                x => new
                                {
                                    Name = x.Key,
                                    EventsCount = x.Count(),
                                    LgE = 4 + 1.8 * x.Max(o => o.Magnitude)
                                })
                            .ToList()
                    })
                .SelectMany(
                    e => e.Months,
                    (e, month) => new DistributionGraphDto
                    {
                        Year = e.Year,
                        Month = month.Name,
                        EventsCount = month.EventsCount,
                        LgE = month.LgE
                    });
        }
    }
}

WebCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://js.arcgis.com/4.10/esri/css/main.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @*@Styles.Render("~/Content/css")*@
    <link rel="stylesheet" href="~/Styles/bootstrap.css" />
    <link rel="stylesheet" href="~/Styles/Site.css" />
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Arkhangelsk seismic network monitoring results</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Map", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Graphs", "Graph", "Home", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    <script type="text/javascript" src="~/Scripts/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="~/Scripts/moment.js"></script>
    @*@Scripts.Render("~/bundles/bootstrap")*@
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>